title = 'LEGACYLIGAN'
baseURL = "https://legacyligan.se"
theme = 'ananke'
resourceDir = "../resources"


languageCode = 'en-us'
DefaultContentLanguage = "sv"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages]
  [languages.sv]
    title = "LEGACYLIGAN.se"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Legacy varje månad"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
  featured_image_class = "cover bg-top"
  # choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
  cover_dimming_class = "bg-black-60"
  recent_posts_number = 3

  custom_css = ["table.css"]

[params.ananke.social.follow]
networks = [
  "twitch",
  "twitter",
  "instagram",
  "youtube",
  "discord",
  "github"
]

[params.ananke.social.twitch]
username = "legacyligan"

[params.ananke.social.twitter]
username = "legacyligan"

[params.ananke.social.instagram]
username = "legacyligan"

[params.ananke.social.youtube]
profilelink = "https://www.youtube.com/channel/UCNpnzSbeGiZpvSnyUdS3QCQ"

[params.ananke.social.discord]
username = "ZKZMnAafVR"

[params.ananke.social.github]
username = "Soren90/legacyligan"
