#baseURL = 'https://legacyligan.se/'
languageCode = 'en-us'
title = 'LEGACYLIGAN'
theme = 'ananke'

baseURL = "https://legacyligan.se"
resourceDir = "../resources"

DefaultContentLanguage = "sv"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.sv]
    title = "LEGACYLIGAN.se"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Legacy varje månad"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  custom_css = ["table.css"]


[[params.ananke_socials]]
name = "twitch"
url = "https://www.twitch.tv/legacyligan"
color = '#6441a4'
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/legacyligan"
[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/legacyligan"
[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCNpnzSbeGiZpvSnyUdS3QCQ"
[[params.ananke_socials]]
name = "discord"
url = "https://discord.gg/ZKZMnAafVR"
color = "#7289da"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/Soren90/legacyligan"
